sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: take-out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    bucket-name: take-out777
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10